// ============================================================================
// FEA MESH EXPORT
// ============================================================================
// Mesh'i standart FEA dosya format'larına dışa aktar:
//   - Abaqus .inp (ASCII keyword tabanlı)
//   - NASTRAN .nas (free-field)
//   - VTK .vtk (legacy ASCII, ParaView uyumlu)
//
// Tüm fonksiyonlar string döner — kaydetme/indirme UI tarafında yapılır.
// Named selections Abaqus'ta *NSET, NASTRAN'da SET cards, VTK'da skip.
//
// Public API:
//   veFEAExportAbaqus(meshData)    → string (.inp)
//   veFEAExportNASTRAN(meshData)   → string (.nas)
//   veFEAExportVTK(meshData)       → string (.vtk)
//   veFEADownloadMeshExport(meshData, format, fileName) — Blob → click
// ============================================================================

// Eleman tipi eşlemeleri
var VE_FEA_ABAQUS_ETYPE = {
  'tet4':    'C3D4',
  'tet10':   'C3D10',
  'hex8':    'C3D8',
  'hex20':   'C3D20',
  'wedge6':  'C3D6',
  'wedge15': 'C3D15',
  'tri3':    'S3'
};
var VE_FEA_NASTRAN_ETYPE = {
  'tet4':    'CTETRA',
  'tet10':   'CTETRA',
  'hex8':    'CHEXA',
  'hex20':   'CHEXA',
  'wedge6':  'CPENTA',
  'wedge15': 'CPENTA',
  'tri3':    'CTRIA3'
};
var VE_FEA_VTK_CELL_TYPE = {
  'tet4':    10,
  'tet10':   24,
  'hex8':    12,
  'hex20':   25,
  'wedge6':  13,
  'wedge15': 26,
  'tri3':    5
};

// ─── Abaqus .inp ───────────────────────────────────────────────────────────
function veFEAExportAbaqus(meshData) {
  if (!meshData || meshData.error) return null;
  var eType = VE_FEA_ABAQUS_ETYPE[meshData.type];
  if (!eType) return null;
  var nodes = meshData.nodes;
  var elements = meshData.elements;
  var per = meshData.nodesPerElement;
  var nNode = nodes.length / 3;
  var nElem = elements.length / per;

  var lines = [];
  lines.push('** Abaqus mesh export — generated by MFSim');
  lines.push('** Element type: ' + meshData.type + ' → ' + eType);
  lines.push('** Nodes: ' + nNode + ', Elements: ' + nElem);
  if (meshData.geometryType) lines.push('** Geometry: ' + meshData.geometryType);
  lines.push('*HEADING');
  lines.push('MFSim FEA Mesh Export');
  lines.push('*NODE');
  for (var i = 0; i < nNode; i++) {
    lines.push((i + 1) + ', ' +
      nodes[i * 3].toFixed(6) + ', ' +
      nodes[i * 3 + 1].toFixed(6) + ', ' +
      nodes[i * 3 + 2].toFixed(6));
  }
  lines.push('*ELEMENT, TYPE=' + eType + ', ELSET=ALL');
  for (var e = 0; e < nElem; e++) {
    var row = [String(e + 1)];
    for (var v = 0; v < per; v++) {
      row.push(String(elements[e * per + v] + 1));
    }
    lines.push(row.join(', '));
  }
  // Named selections → *NSET
  if (meshData.namedSelections) {
    Object.keys(meshData.namedSelections).forEach(function(k) {
      var ns = meshData.namedSelections[k];
      if (!ns.nodeIds || ns.nodeIds.length === 0) return;
      var setName = k.replace(/[^A-Za-z0-9_]/g, '_').toUpperCase().slice(0, 80);
      lines.push('*NSET, NSET=' + setName);
      // Her satıra max 16 ID (Abaqus convention)
      for (var s = 0; s < ns.nodeIds.length; s += 16) {
        var chunk = [];
        for (var j = s; j < Math.min(s + 16, ns.nodeIds.length); j++) {
          chunk.push(String(ns.nodeIds[j] + 1));
        }
        lines.push(chunk.join(', '));
      }
    });
  }
  lines.push('*END STEP');
  return lines.join('\n');
}

// ─── NASTRAN .nas / .bdf (free-field) ──────────────────────────────────────
function veFEAExportNASTRAN(meshData) {
  if (!meshData || meshData.error) return null;
  var eCard = VE_FEA_NASTRAN_ETYPE[meshData.type];
  if (!eCard) return null;
  var nodes = meshData.nodes;
  var elements = meshData.elements;
  var per = meshData.nodesPerElement;
  var nNode = nodes.length / 3;
  var nElem = elements.length / per;
  var pid = 1; // Property ID (single material assumed)

  var lines = [];
  lines.push('$ NASTRAN free-field mesh export — generated by MFSim');
  lines.push('$ Element type: ' + meshData.type + ' → ' + eCard);
  lines.push('$ Nodes: ' + nNode + ', Elements: ' + nElem);
  lines.push('BEGIN BULK');
  // GRID kartları
  for (var i = 0; i < nNode; i++) {
    lines.push('GRID,' + (i + 1) + ',,' +
      nodes[i * 3].toFixed(6) + ',' +
      nodes[i * 3 + 1].toFixed(6) + ',' +
      nodes[i * 3 + 2].toFixed(6));
  }
  // Element kartları
  for (var e = 0; e < nElem; e++) {
    var fields = [eCard, String(e + 1), String(pid)];
    for (var v = 0; v < per; v++) {
      fields.push(String(elements[e * per + v] + 1));
    }
    lines.push(fields.join(','));
  }
  // PSOLID + MAT1 (default material, kullanıcı sonra güncelleyebilir)
  lines.push('PSOLID,' + pid + ',1');
  lines.push('MAT1,1,210000.0,,0.3,7.85e-9');
  lines.push('ENDDATA');
  return lines.join('\n');
}

// ─── VTK Legacy ASCII ──────────────────────────────────────────────────────
function veFEAExportVTK(meshData) {
  if (!meshData || meshData.error) return null;
  var cellType = VE_FEA_VTK_CELL_TYPE[meshData.type];
  if (cellType === undefined) return null;
  var nodes = meshData.nodes;
  var elements = meshData.elements;
  var per = meshData.nodesPerElement;
  var nNode = nodes.length / 3;
  var nElem = elements.length / per;

  var lines = [];
  lines.push('# vtk DataFile Version 3.0');
  lines.push('MFSim FEA Mesh Export — ' + meshData.type + (meshData.geometryType ? ' (' + meshData.geometryType + ')' : ''));
  lines.push('ASCII');
  lines.push('DATASET UNSTRUCTURED_GRID');
  lines.push('POINTS ' + nNode + ' float');
  for (var i = 0; i < nNode; i++) {
    lines.push(
      nodes[i * 3].toFixed(6) + ' ' +
      nodes[i * 3 + 1].toFixed(6) + ' ' +
      nodes[i * 3 + 2].toFixed(6)
    );
  }
  // CELLS: total = nElem * (1 + per) integers
  var totalCellSize = nElem * (1 + per);
  lines.push('CELLS ' + nElem + ' ' + totalCellSize);
  for (var e = 0; e < nElem; e++) {
    var row = [String(per)];
    for (var v = 0; v < per; v++) {
      row.push(String(elements[e * per + v]));
    }
    lines.push(row.join(' '));
  }
  lines.push('CELL_TYPES ' + nElem);
  for (var e2 = 0; e2 < nElem; e2++) lines.push(String(cellType));
  return lines.join('\n');
}

// ─── Browser download köprüsü ──────────────────────────────────────────────
function veFEADownloadMeshExport(meshData, format, fileName) {
  if (!meshData) return false;
  var content, ext, mime;
  if (format === 'abaqus') {
    content = veFEAExportAbaqus(meshData);
    ext = '.inp';
    mime = 'text/plain';
  } else if (format === 'nastran') {
    content = veFEAExportNASTRAN(meshData);
    ext = '.nas';
    mime = 'text/plain';
  } else if (format === 'vtk') {
    content = veFEAExportVTK(meshData);
    ext = '.vtk';
    mime = 'text/plain';
  } else {
    return false;
  }
  if (!content) {
    if (typeof showToast === 'function') showToast('Bu mesh tipi ' + format + ' export\'unu desteklemiyor', 'warning');
    return false;
  }
  if (typeof document === 'undefined' || typeof URL === 'undefined' || typeof Blob === 'undefined' ||
      typeof URL.createObjectURL !== 'function') {
    return content; // test ortamı (jsdom) — string döner
  }
  var blob = new Blob([content], { type: mime });
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url;
  a.download = (fileName || 'mesh') + ext;
  document.body.appendChild(a);
  a.click();
  setTimeout(function() {
    URL.revokeObjectURL(url);
    if (a.parentNode) a.parentNode.removeChild(a);
  }, 100);
  return true;
}

// UI köprüsü — cp-fea.js'ten çağrılır
function veFEAExportMeshForNode(meshNodeId, format) {
  if (typeof veFEAMeshCache === 'undefined') return false;
  var meshData = veFEAMeshCache[meshNodeId];
  if (!meshData) {
    if (typeof showToast === 'function') showToast('Mesh oluşturulmamış — önce mesh\'i hesaplayın', 'warning');
    return false;
  }
  var ok = veFEADownloadMeshExport(meshData, format, 'mesh-' + meshNodeId);
  if (ok && typeof showToast === 'function') {
    showToast('Mesh export tamamlandı (' + format + ')', 'success');
  }
  return ok;
}
